spring.application.name=DBMS

# Server Port
server.port=5000

# PostgreSQL (JPA) Configuration
# Converted from your connection string
spring.datasource.url=jdbc:postgresql://db.prisma.io:5432/postgres?sslmode=require
spring.datasource.username=a7fe9d8bc3ddb78bb697b92542767cb9af6384e6b34277c960624370418f94d4
spring.datasource.password=sk_vCRdjIDfMjCb_2zJzAOBi
spring.jpa.hibernate.ddl-auto=update

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://amanrajesh:amanrajesh123@cluster0.4uxwqcx.mongodb.net/librarydb

# JWT Secret
jwt.secret=your-very-strong-and-long-jwt-secret-key-that-is-at-least-256-bits
jwt.expiration-ms=604800000